version: "3.9"

services:
  service_a:
    build:
      context: .
      dockerfile: docker/Dockerfile.a
    ports:
      - "443:8001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - ./certs:/app/certs
    command: ["uvicorn", "service_a.main:app", "--host", "0.0.0.0", "--port", "8001", "--ssl-keyfile", "/app/certs/localhost.key", "--ssl-certfile", "/app/certs/localhost.crt"]
    restart: always

  service_b:
    build:
      context: .
      dockerfile: docker/Dockerfile.b
    ports:
      - "444:8002"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - ./certs:/app/certs
    command: ["uvicorn", "service_b.main:app", "--host", "0.0.0.0", "--port", "8002", "--ssl-keyfile", "/app/certs/localhost.key", "--ssl-certfile", "/app/certs/localhost.crt"]
    restart: always

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
