FROM python:3.11-slim

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /app

COPY ./service_a ./service_a

CMD ["uvicorn", "service_a.main:app", "--host", "0.0.0.0", "--port", "8001"]
