FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /app

COPY ./service_a ./service_a

COPY ./certs/localhost.crt /etc/ssl/certs/service_a.crt
COPY ./certs/localhost.key /etc/ssl/private/service_a.key

CMD ["uvicorn", "service_a.main:app", "--host", "0.0.0.0", "--port", "8001", "--ssl-keyfile", "/etc/ssl/private/service_a.key", "--ssl-certfile", "/etc/ssl/certs/service_a.crt"]
